### PR TITLE
Better rhs handling. More Methods.

### PR DESCRIPTION
**Pull request by drungrin**
Implemented default behavior of SingleOrDefault and FirstOrDefault. Still need to implement DefaultIfEmpty to add custom behavior
Better rhs handling on BinaryExpression

### CODE REVIEW

**Comment by kristiandupont** [comment]
This is great. Could you write a couple of tests for it?

**Comment by drungrin** [comment]
Right now I cann't.
I suspended the project that uses Realm, I had another priority.
I'll get back asap.

**Comment by kristiandupont** [comment]
Fair enough. I'll keep this open.

**Comment by fealebenpae** [comment]
@drungrin I'm closing this as it seems to be stale now. Please feel free to open it again at a later date.

**Pull request closed without merging**
