### PR TITLE
Fix `TraverseSort` to support properties declared by interfaces

### PR DESCRIPTION
**Pull request by daawaan**
## Description

Fixes https://github.com/realm/realm-dotnet/issues/1373

##  TODO

* [ ] Changelog entry
* [ ]

## Questions

I'm a first time contributor and I would like to ask what are changelog entries specifically?

### CODE REVIEW

**Comment by nirinchev** [comment]
Hey @daawaan, thanks for the PR and sorry for the delay in getting this reviewed - most of the team has been off around the holidays. The change makes sense to me, but we'll need to review it more thoroughly to ensure it doesn't break existing behavior.

It appears our CI setup doesn't work well for outside contributors, so we'll need to run the tests manually. @papafe can you take point on this?

**Comment by papafe** [comment]
@nirinchev I can run the tests locally, but we need to see how can make CI work for external contributors. 
Just the last couple of weeks me and @LaPeste were looking at a LINQ problem, and there was an issue where some nodes were actually of different types on different environments. So we definitely need the CI to be sure this fix works everywhere

**Comment by papafe** [comment]
@daawaan To answer your question, changelog entries refer to the `CHANGELOG.md` file, where we log all the bug fixes and enhancements that are added in a certain version. We can take care of that ourselves at the end, no problem.

**Comment by papafe** [comment]
The CI is green on the PR with the same code, so this could be merged. @nirinchev do we fix the changelog in another PR after this is merged?

**Comment by nirinchev** [comment]
Let's merge this and fix the changelog as a follow-up

**Review by papafe — APPROVED** [review]

**Pull request merged**
