### PR TITLE
Refactor and extract AssemblyInfo.cs files

### PR DESCRIPTION
**Pull request by fealebenpae**
Extract all the common parts of all the various AssemblyInfo files in a central one. This makes it easier to stamp versions in CI.

### CODE REVIEW

**Comment by kristiandupont** [comment]
:+1:

**Comment by AndyDentFree** [comment]
Where does the assemblyVersion now come from? Does this mean the source lacks it altogether?
I would have expected it to be in `realm-dotnet/RealmAssemblyInfo.cs`

**Comment by fealebenpae** [comment]
The CI job that will build the nuget package accepts a version string as a parameter and appends the `AssemblyVersion` and `AssemblyFileVersion` attributes to `RealmAssemblyInfo.cs` along with the build number.

**Comment by AndyDentFree** [comment]
Yeah, I don't like that - it means there's no record in source control of what version the assembly was tagged with. That also seems contrary to the other products - Cocoa has a `Realm-info.plist` and Java has `version.txt`

**Comment by fealebenpae** [comment]
That's cool, we can still have the version in the source.

**Pull request merged**
