### PR TITLE
Ad/weaver write persist attribute#822

### PR DESCRIPTION
**Pull request by AndyDentFree**
@fealebenpae please review.
Tried adding the equivalent of `[Persist(allMembers=true)]` to type but that seems insufficient so ended up adding a simple `[Persist]` on all woven members.

### CODE REVIEW

**Comment by nirinchev** [comment]
It seems counter-intuitive that we add a `[Preserve]` to all properties and the default ctor AND a `[Preserve(AllMembers = true)]` to the type.

You say that `Preserve(true)` is insufficient - does it fail on iOS/Android/both?

**Comment by AndyDentFree** [comment]
It has only ever failed on IOS. Yes it seems counter-intuitive and I could strip it back a bit and just put the simple `[Preserve]` on the type but thought I may as well leave that in there in case it helps - I don't think it can cause any harm.

I have spent far more time on this particular issue than I am happy with, and the brute force approach of putting it on all properties is the only thing I could get to work with full linking.

**Comment by AndyDentFree** [comment]
retest this please

**Comment by AndyDentFree** [comment]
retest this please

**Pull request merged**
