### PR TITLE
Ad/bug migration needed exception #507

### PR DESCRIPTION
**Pull request by AndyDentFree**
Minor change just to catch the exception currently being thrown from ObjectStore and map it to our desire C# exception.

@fealebenpae or @kristiandupont please review

**NOTE** this does **not** fix our `MigrationTriggersDelete` test as that crashes due to schema issues.

### CODE REVIEW

**Comment by fealebenpae** [comment]
I think we need a new error type for this: `FileFormatUpgradeRequired ` will be thrown by core when the realm uses a deprecated file format in need of upgrade and automatic updates have been explicitly disabled, and it will be translated by object store to `FormatUpgradeRequired`. It has nothing to do with the schema in object store.

**Comment by AndyDentFree** [comment]
Well, this is a relatively quick fix for a common user mistake and to align with what is being thrown by ObjectStore right now. I can dig deeper and push for a commonly accepted OS fix to do a unique exception but that is (literally) a separate issue.

**Comment by fealebenpae** [comment]
I don't propose changing object store - just add a new member to the enum in `realm_error_type.hpp` and use that. OS already has distinct exception types - we're the ones that conflate them under a single error type when marshalling to c#.

**Comment by AndyDentFree** [comment]
> I don't propose changing object store

The point is that objectStore is throwing the _wrong_ exception in the first place.

**Comment by fealebenpae** [comment]
> objectStore is throwing the wrong exception in the first place

Oh, I was under the impression that `SchemaMismatchException` is the intended exception type.

**Comment by AndyDentFree** [comment]
Sorry, you are right - I was looking at old notes - the thing which **is** wrong is that we are overloading `FileFormatUpgradeRequired` because previously, that **was** the _wrongly returned_ error.

**Comment by fealebenpae** [comment]
👍

**Comment by kristiandupont** [comment]
:+1:

**Pull request merged**
