### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by papafe**
Fixes bad link and some wording

Fixes #3082

### CODE REVIEW

**Comment by LaPeste** [comment]
What bad link is this fixing? It just removes the link to source, which was correctly pointing to the Realm .NET repo.

**Comment by papafe** [comment]
> What bad link is this fixing? It just removes the link to source, which was correctly pointing to the Realm .NET repo.
> 
> EDIT: I can see that this issue comes from #3082 . I guess that what we're tying to say is that we don't need to link to the repo since we're already in the repo?

Yes, it doesn't make sense to link to the same repo in which we are already in.

**Review by LaPeste — APPROVED** [review]

**Comment by papafe** [comment]
@nirinchev anything against merging this?

**Comment by nirinchev** [comment]
No, go for it

**Pull request merged**
